apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
  - image: "identity-platform-admin-ui"
    sync:
      infer:
      - "internal/"
      - "pkg/"
      - "cmd/main.go"
      - "go.mod"
      - "go.sum"
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - rockcraft.yaml
    platforms: ["linux/amd64"]
  local:
    push: true

test:
  - image: "identity-platform-admin-ui"
    structureTests:
      - './structure-tests.yaml'


manifests:
  rawYaml:
    - "deployments/kubectl/*"

deploy:
  statusCheck: true
  statusCheckDeadlineSeconds: 180
  tolerateFailuresUntilDeadline: true
  kubectl: {}
  helm:
    releases:
      - name: postgresql
        remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
        valuesFiles: ["deployments/helm/postgresql/values.yaml"]
      - name: kratos
        remoteChart: kratos
        repo: https://k8s.ory.sh/helm/charts
        valuesFiles: ["deployments/helm/kratos/values.yaml"]
        wait: false
      - name: hydra
        remoteChart: hydra
        repo: https://k8s.ory.sh/helm/charts
        valuesFiles: ["deployments/helm/hydra/values.yaml"]
        wait: false
      - name: openfga
        remoteChart: openfga
        repo: https://openfga.github.io/helm-charts
        valuesFiles: ["deployments/helm/openfga/values.yaml"]
        wait: false
      - name: mailhog
        remoteChart: mailhog
        repo: https://codecentric.github.io/helm-charts
        valuesFiles: ["deployments/helm/mailhog/values.yaml"]

portForward:
- resourceType: service
  resourceName: identity-platform-admin-ui
  namespace: default
  port: 80
  localPort: 8000
- resourceType: service
  resourceName: kratos-admin
  namespace: default
  port: 80
  localPort: 14434
- resourceType: service
  resourceName: kratos-public
  namespace: default
  port: 80
  localPort: 14433
- resourceType: service
  resourceName: hydra-admin
  namespace: default
  port: 4445
  localPort: 14445
- resourceType: service
  resourceName: hydra-public
  namespace: default
  port: 4444
  localPort: 4444
- resourceType: service
  resourceName: openfga
  namespace: default
  port: 8080
  localPort: 14457
- resourceType: service
  resourceName: mailhog
  namespace: default
  port: 8025
  localPort: 18025
- resourceType: service
  resourceName: postgresql
  namespace: default
  port: 5432
  localPort: 15432
