demo: false
maester:
  enabled: false
service:
  proxy:
    enabled: false
  metrics:
    enabled: false
oathkeeper:
  managedAccessRules: false
  config:
    access_rules:
      repositories:
        - file:///etc/rules/admin_ui_rules.json
    authenticators:
      anonymous:
        enabled: true
      jwt:
        enabled: true
        config:
          jwks_urls:
            - "https://raw.githubusercontent.com/ory/k8s/master/helm/charts/oathkeeper/demo/authenticator.jwt.jwks.json"
      noop:
        enabled: true
      unauthorized:
        enabled: true
    authorizers:
      allow:
        enabled: true
      deny:
        enabled: true
    mutators:
      cookie:
        enabled: true
        config:
          cookies:
            user: "<nil>"
      header:
        enabled: true
        config:
          headers:
            X-User: "<nil>"
      id_token:
        enabled: true
        config:
          issuer_url: http://oathkeeper/
          jwks_url: https://raw.githubusercontent.com/ory/k8s/master/helm/charts/oathkeeper/demo/mutator.id_token.jwks.json
      noop:
        enabled: true
    serve:
      proxy:
        cors:
          enabled: true
      api:
        cors:
          enabled: true