export enum Label {
  AUTH_URL = "Auth URL",
  CLIENT_ID = "Client ID",
  CLIENT_SECRET = "Client secret",
  DEVELOPER_TEAM_ID = "Developer Team ID",
  MAPPER = "Mapper",
  ME = "Me",
  NAME = "Name",
  NO = "No",
  OIDC_SERVER_URL = "OIDC server URL",
  PRIVATE_KEY = "Private Key",
  PRIVATE_KEY_ID = "Private Key ID",
  PROVIDER = "Provider",
  REQUESTED_CLAIMS = "Requested claims",
  SCOPES = "Scopes",
  TENANT = "Tenant",
  TOKEN_URL = "Token URL",
  USERINFO = "Userinfo",
  YES = "Yes",
}
