// Package resources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for CapabilityMethods.
const (
	DELETE CapabilityMethods = "DELETE"
	GET    CapabilityMethods = "GET"
	PATCH  CapabilityMethods = "PATCH"
	POST   CapabilityMethods = "POST"
)

// Defines values for EntityEntitlementPatchItemOp.
const (
	EntityEntitlementPatchItemOpAdd    EntityEntitlementPatchItemOp = "add"
	EntityEntitlementPatchItemOpRemove EntityEntitlementPatchItemOp = "remove"
)

// Defines values for IdentityProviderSyncMode.
const (
	Import IdentityProviderSyncMode = "import"
)

// Defines values for PatchRequestBodyOp.
const (
	PatchRequestBodyOpAdd    PatchRequestBodyOp = "add"
	PatchRequestBodyOpRemove PatchRequestBodyOp = "remove"
)

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Data []Capability `json:"data"`
}

// Capability defines model for Capability.
type Capability struct {
	Endpoint string              `json:"endpoint"`
	Methods  []CapabilityMethods `json:"methods"`
}

// CapabilityMethods defines model for Capability.Methods.
type CapabilityMethods string

// Entitlement defines model for Entitlement.
type Entitlement = string

// Entity defines model for Entity.
type Entity = map[string]interface{}

// EntityEntitlement defines model for EntityEntitlement.
type EntityEntitlement struct {
	Entitlement *Entitlement `json:"entitlement,omitempty"`
	Entity      *Entity      `json:"entity,omitempty"`
	Id          *string      `json:"id,omitempty"`
}

// EntityEntitlementPatchItem defines model for EntityEntitlementPatchItem.
type EntityEntitlementPatchItem struct {
	Op    EntityEntitlementPatchItemOp `json:"op"`
	Value []EntityEntitlement          `json:"value"`
}

// EntityEntitlementPatchItemOp defines model for EntityEntitlementPatchItem.Op.
type EntityEntitlementPatchItemOp string

// EntityEntitlementPatchRequestBody defines model for EntityEntitlementPatchRequestBody.
type EntityEntitlementPatchRequestBody = []EntityEntitlementPatchItem

// EntityEntitlements defines model for EntityEntitlements.
type EntityEntitlements struct {
	Data []EntityEntitlement `json:"data"`
}

// GetCapabilitiesResponse defines model for GetCapabilitiesResponse.
type GetCapabilitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Capability  `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetEntitlementsResponse defines model for GetEntitlementsResponse.
type GetEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupEntitlementsResponse defines model for GetGroupEntitlementsResponse.
type GetGroupEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupIdentitiesResponse defines model for GetGroupIdentitiesResponse.
type GetGroupIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupRolesResponse defines model for GetGroupRolesResponse.
type GetGroupRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupsResponse defines model for GetGroupsResponse.
type GetGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentitiesResponse defines model for GetIdentitiesResponse.
type GetIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityEntitlementsResponse defines model for GetIdentityEntitlementsResponse.
type GetIdentityEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetIdentityGroupsResponse defines model for GetIdentityGroupsResponse.
type GetIdentityGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityProvidersResponse defines model for GetIdentityProvidersResponse.
type GetIdentityProvidersResponse struct {
	Links ResponseLinks `json:"_links"`
	Meta  ResponseMeta  `json:"_meta"`
	Data  []struct {
		Id   string `json:"id"`
		Name string `json:"name"`
	} `json:"data"`
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// GetIdentityRolesResponse defines model for GetIdentityRolesResponse.
type GetIdentityRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetResourcesResponse defines model for GetResourcesResponse.
type GetResourcesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Resource    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetRoleEntitlementsResponse defines model for GetRoleEntitlementsResponse.
type GetRoleEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetRolesResponse defines model for GetRolesResponse.
type GetRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// Group defines model for Group.
type Group struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name"`
}

// Groups defines model for Groups.
type Groups struct {
	Data []Group `json:"data"`
}

// Identities defines model for Identities.
type Identities struct {
	Data []Identity `json:"data"`
}

// Identity defines model for Identity.
type Identity struct {
	AddedBy     string  `json:"addedBy"`
	Certificate *string `json:"certificate,omitempty"`
	Email       string  `json:"email"`
	FirstName   *string `json:"firstName,omitempty"`
	Groups      *int    `json:"groups,omitempty"`
	Id          *string `json:"id,omitempty"`
	Joined      *string `json:"joined,omitempty"`
	LastLogin   *string `json:"lastLogin,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Permissions *int    `json:"permissions,omitempty"`
	Roles       *int    `json:"roles,omitempty"`
	Source      string  `json:"source"`
}

// IdentityProvider defines model for IdentityProvider.
type IdentityProvider struct {
	AcceptsPromptNone   *bool                     `json:"acceptsPromptNone,omitempty"`
	AccountLinkingOnly  *bool                     `json:"accountLinkingOnly,omitempty"`
	ClientID            *string                   `json:"clientID,omitempty"`
	ClientSecret        *string                   `json:"clientSecret,omitempty"`
	DisableIdentityInfo *bool                     `json:"disableIdentityInfo,omitempty"`
	Enabled             *bool                     `json:"enabled,omitempty"`
	Id                  *string                   `json:"id,omitempty"`
	IdentityCount       *int                      `json:"identityCount,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	RedirectUrl         *string                   `json:"redirectUrl,omitempty"`
	StoreTokens         *bool                     `json:"storeTokens,omitempty"`
	StoreTokensReadable *bool                     `json:"storeTokensReadable,omitempty"`
	SyncMode            *IdentityProviderSyncMode `json:"syncMode,omitempty"`
	TrustEmail          *bool                     `json:"trustEmail,omitempty"`
}

// IdentityProviderSyncMode defines model for IdentityProvider.SyncMode.
type IdentityProviderSyncMode string

// PatchGroupEntitlementsResponse defines model for PatchGroupEntitlementsResponse.
type PatchGroupEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// PatchGroupIdentitiesResponse defines model for PatchGroupIdentitiesResponse.
type PatchGroupIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// PatchGroupRolesResponse defines model for PatchGroupRolesResponse.
type PatchGroupRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// PatchIdentityEntitlementsResponse defines model for PatchIdentityEntitlementsResponse.
type PatchIdentityEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// PatchIdentityGroupsResponse defines model for PatchIdentityGroupsResponse.
type PatchIdentityGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// PatchIdentityRolesResponse defines model for PatchIdentityRolesResponse.
type PatchIdentityRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// PatchRequestBody defines model for PatchRequestBody.
type PatchRequestBody = []struct {
	Op    PatchRequestBodyOp           `json:"op"`
	Value PatchRequestBodyElementValue `json:"value"`
}

// PatchRequestBodyOp defines model for PatchRequestBody.Op.
type PatchRequestBodyOp string

// PatchRequestBodyElementValue defines model for PatchRequestBodyElementValue.
type PatchRequestBodyElementValue = []PatchRequestBodyElementValueItem

// PatchRequestBodyElementValueItem defines model for PatchRequestBodyElementValueItem.
type PatchRequestBodyElementValueItem struct {
	Id string `json:"id"`
}

// PatchRoleEntitlementsResponse defines model for PatchRoleEntitlementsResponse.
type PatchRoleEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// Resource defines model for Resource.
type Resource struct {
	Entity Entity    `json:"entity"`
	Id     string    `json:"id"`
	Name   string    `json:"name"`
	Parent *Resource `json:"parent,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	Data []Resource `json:"data"`
}

// Response defines model for Response.
type Response struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// ResponseLinks defines model for ResponseLinks.
type ResponseLinks struct {
	Next ResponseLinksNext `json:"next"`
}

// ResponseLinksNext defines model for ResponseLinksNext.
type ResponseLinksNext struct {
	Href string `json:"href"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Page      *int    `json:"page,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	Size      int     `json:"size"`
	Total     *int    `json:"total,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Entitlements *[]RoleEntitlement `json:"entitlements,omitempty"`
	Id           *string            `json:"id,omitempty"`
	Name         string             `json:"name"`
}

// RoleEntitlement defines model for RoleEntitlement.
type RoleEntitlement struct {
	Entitlement *string `json:"entitlement,omitempty"`
	Entity      *Entity `json:"entity,omitempty"`
	Resource    *string `json:"resource,omitempty"`
}

// Roles defines model for Roles.
type Roles struct {
	Data []Role `json:"data"`
}

// FilterParam defines model for FilterParam.
type FilterParam = string

// PaginationNextToken defines model for PaginationNextToken.
type PaginationNextToken = string

// PaginationPage defines model for PaginationPage.
type PaginationPage = int

// PaginationSize defines model for PaginationSize.
type PaginationSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Response

// NotFound defines model for NotFound.
type NotFound = Response

// Unauthorized defines model for Unauthorized.
type Unauthorized = Response

// Default defines model for default.
type Default = Response

// GetAuthenticationParams defines parameters for GetAuthentication.
type GetAuthenticationParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetAuthenticationProvidersParams defines parameters for GetAuthenticationProviders.
type GetAuthenticationProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetEntitlementsParams defines parameters for GetEntitlements.
type GetEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetGroupsParams defines parameters for GetGroups.
type GetGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetGroupsItemEntitlementsParams defines parameters for GetGroupsItemEntitlements.
type GetGroupsItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetGroupsItemIdentitiesParams defines parameters for GetGroupsItemIdentities.
type GetGroupsItemIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetGroupsItemRolesParams defines parameters for GetGroupsItemRoles.
type GetGroupsItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetIdentitiesParams defines parameters for GetIdentities.
type GetIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetIdentitiesItemEntitlementsParams defines parameters for GetIdentitiesItemEntitlements.
type GetIdentitiesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetIdentitiesItemGroupsParams defines parameters for GetIdentitiesItemGroups.
type GetIdentitiesItemGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetIdentitiesItemRolesParams defines parameters for GetIdentitiesItemRoles.
type GetIdentitiesItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// GetResourcesParams defines parameters for GetResources.
type GetResourcesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken  *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	EntityType *string              `form:"entityType,omitempty" json:"entityType,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`
}

// GetRolesItemEntitlementsParams defines parameters for GetRolesItemEntitlements.
type GetRolesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
}

// PostAuthenticationJSONRequestBody defines body for PostAuthentication for application/json ContentType.
type PostAuthenticationJSONRequestBody = IdentityProvider

// PutAuthenticationItemJSONRequestBody defines body for PutAuthenticationItem for application/json ContentType.
type PutAuthenticationItemJSONRequestBody = IdentityProvider

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody = Group

// PutGroupsItemJSONRequestBody defines body for PutGroupsItem for application/json ContentType.
type PutGroupsItemJSONRequestBody = Group

// PatchGroupsItemEntitlementsJSONRequestBody defines body for PatchGroupsItemEntitlements for application/json ContentType.
type PatchGroupsItemEntitlementsJSONRequestBody = EntityEntitlementPatchRequestBody

// PatchGroupsItemIdentitiesJSONRequestBody defines body for PatchGroupsItemIdentities for application/json ContentType.
type PatchGroupsItemIdentitiesJSONRequestBody = PatchRequestBody

// PatchGroupsItemRolesJSONRequestBody defines body for PatchGroupsItemRoles for application/json ContentType.
type PatchGroupsItemRolesJSONRequestBody = PatchRequestBody

// PostIdentitiesJSONRequestBody defines body for PostIdentities for application/json ContentType.
type PostIdentitiesJSONRequestBody = Identity

// PutIdentitiesItemJSONRequestBody defines body for PutIdentitiesItem for application/json ContentType.
type PutIdentitiesItemJSONRequestBody = Identity

// PatchIdentitiesItemEntitlementsJSONRequestBody defines body for PatchIdentitiesItemEntitlements for application/json ContentType.
type PatchIdentitiesItemEntitlementsJSONRequestBody = EntityEntitlementPatchRequestBody

// PatchIdentitiesItemGroupsJSONRequestBody defines body for PatchIdentitiesItemGroups for application/json ContentType.
type PatchIdentitiesItemGroupsJSONRequestBody = PatchRequestBody

// PatchIdentitiesItemRolesJSONRequestBody defines body for PatchIdentitiesItemRoles for application/json ContentType.
type PatchIdentitiesItemRolesJSONRequestBody = PatchRequestBody

// PostRolesJSONRequestBody defines body for PostRoles for application/json ContentType.
type PostRolesJSONRequestBody = Role

// PatchRolesItemJSONRequestBody defines body for PatchRolesItem for application/json ContentType.
type PatchRolesItemJSONRequestBody = Role

// PatchRolessItemEntitlementsJSONRequestBody defines body for PatchRolessItemEntitlements for application/json ContentType.
type PatchRolessItemEntitlementsJSONRequestBody = EntityEntitlementPatchRequestBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9W3PbNtZ/BYPve8owlrPNvuhp3SR13U1tj+PsPrSeDkQeSahBgAVAO2pG/30HAO8E",
	"L/JFkSM92SJxOTh3nHMAfsWhiBPBgWuFp19xQiSJQYO0v36iTIO8NM/MzwhUKGmiqeB4ik+Q0pLyBdIC",
	"zW1DJEGlTCs0W+EAU9PorxSk+cFJDHiKXTscYBUuISZmUL1KzBs3Fl6vA3xJFpQTM8s5fNHX4hZ4e/br",
	"JaBQcE15apsibdoZWCRoSeEOkF4C4vBFIwUaiXkOXQdovJhrLHSXZAF+wCSEQkZIzOdmagdTKnmBn7kU",
	"cQcYiRm0CkFMOY3TGE/fBDk0lGtYgGyA84n+3QEOT+MZSIcCA5iqgJQ4siWCK+gASZmBayCRLxlIx8dB",
	"P4DrAOejW476kURX8FcKSptfhoDA7b8kSRgN7UImfyphKQ5fSJwwu6g/GOW3dgRDJ/N3KWGOp9gi4Y8Y",
	"NHHsa0hyHDiYzT9aaMLw9Hgd4IiYRr/dBDgGpWxLAw+SGUABVproVOHp22PTvlzw/7u5/m9SCsvEvVWT",
	"qxx5drF15JvR8+WuA3wu9E8i5dFuLP1caDS34FQX/vZJFl6OvQ7wZ05SvRSS/g07svQaRNXVv3mS1deG",
	"t2/nJGV6V9YOXxIINUQIpBSysv5/PhHbt6ZYF8PaBb0jCZlRRjV1SiFbtcLT377mMH/FwKNEUIMrPKER",
	"cO3am7XopYhMa3z64RrfrG/WNwFOpEhA5kO6Ub5iqiFWQ2sp4FkZamU6jEhJVtgpsL9SKg3v/ubGvSka",
	"idmfEFrZroxhqFIDplxJy6BUVlMBFrjRp255Ab68+GT+vP/w8cP1B/P75PrdzxUgyrF6QS+gKOf0LeSD",
	"QTSDOOPSCm2wBGLEJQKlpTAGgkTR65CJNPJCY0datQhMIzzFaUrNUFkfIxVSMGZMhiFlzQmx7bNRPbNU",
	"l2hfBqZH58pWjfU1KVV72cc01XHWgeu5GtXJchmN/O7FMNSXRIfLMw1xG3yRVLmHRAbFEmJxB14C3RGW",
	"wmgpaaNviONEgvNJbkavLLOXP4po9XDQShy1YPTMq9qY3Eh/bI6ZTjVyCrqqHQsta+wFYxdzK0Hj9HIw",
	"UumZFa9v3NxVpDzj3B4K5BCcSpEmOwLGWWF1nhGIcpL65FeCPeu8dvz6lM85nZugmO9boTZ7tPr2HJZD",
	"8o0wv7qU4o5GIB879YDerL/2Wr18o+kzh1WlaT0G29SnOR+ibxso2a7IXYESqQyfd8Z8jnJWweDbM/82",
	"MW3Y/4k5sZMJM1l7nDvhIH6wC1HReo+DIxeLR4Pi2RKRKILox+bmAIvb2kglXULTdW62y+ClG8SEMu+b",
	"OZVKn/vJGuBFQbBm6CroYpE/BeXgf8WI0h/FgvLOt52AJCBjqhQVvAMaaVna+8rJeBOX8EWD5ITZqF72",
	"bxu1zU2ixWMxZFAQqo+8uSnxkDkMIdHqUoo40eeCV9c+E4IB4WYgEoYi5foj5beULy44W/nbhYwC12fv",
	"vRh0Lz9BKMG/046oIjMGOdRnfC780wA37SL/yw6uyCIUq3dmIX4y8S7aS4iohFB/ln4WVlpIsLFp5Yep",
	"0uAKSGSg72i44uGvIoLqNpHGiZDaH0+QqdIfGqJVDOfbrdqN1y748CUg38TVLKffoqlzu97d8HBrsGzV",
	"x63NvG3sd0UvniZO0wdJc/oPjhz/sX03jMw0Iya9Y491J/oG6QrVDPYZ59e1NxI3XbprB/zj3GnvCE8+",
	"NshYGqKqt0Du1QTS1/eg/KYgIXJEULQAvXvvVoRKfSQo9yuPc11LOB7qulbpXgekTMyM4YKPtnE1YzOm",
	"16+m7bqStvF6BS5r89WXFq6uMWuYgxDkKyiH70PAx3y1dSzkSanRODg3HVobKfNwcPbzbK46BC4dNiTr",
	"tlXfDL/mibTa4Ekd6xUvzrwpahLaRMmS8O1+WVpumFpmBC/AgkFvxkKNF4+6kvNp3ufZHzcnHkrAtPd5",
	"G2pAWdGlI5ItV/km6zG6x9DpgXrHNKPZviQUXJPQJeGcC45ZegtH96AYrF4vBWOw+ldIuOA0JOwotDUl",
	"Wc3Gx/QW0H9dy59tS9xK014vAc0FY+Ke8gVSCYRuh00FRyLVjHJQtojm5PIM5cCjuZD24U+nJ4hEMeVU",
	"aek6zaXNbkdIC2S3nCTU6J7qJSIcXSTATR/KlSY8BKSXUqSLJSIokSJKQ63MREfoekkVosr0gTvB7trA",
	"EYUkzJnLMFNuwbkDaTbPWa3L0e8cB9iyEp7idzmOCiBO6oBfOgDQOxEnRFOXxzXQGC/JDYyn+Pjo+OjN",
	"scGjSICThOIp/uHozdExNlpBLy1nTEiql4ZLHazm0cLtR5vIpwrlKVnEqNIKEcZQtvc0OHHhWbcUw412",
	"wLMIT/Ep6JP6NPWkaYeHUjaZNMqGulwVbw9b97RRj7KOa33TKAj6x/HxiLqIcTUJvdFtT53Cxb8NMd86",
	"CHwDF5BOKnVLtsub4S7NKpC3x2+HOxUlQvWykf5OeUNbZpHGMZErowKo0igUfE4XqRHcOmNWGMxIClk4",
	"L7DOVcYbTYTysO+7fFxEEIf7rsGPWqx7KVSbd2V91/QkzNAKTq3rOljLFNbPyIz++feJATfgkU7+WwdN",
	"jTopGHekblVLkbIor3ckVtciMc/nV+iWi3tbOWrsiFopDXFgzVy2P0IXt5oE6FSIBYMAnVL9czpDoMOj",
	"39Pj4x/CmUQT+x/8zl+9ur54f/Hq1RS9Rp+s0VrZYbPZjbkfo88L9bU/iv3pU49PlCLcN7G9sqzqPL9c",
	"VlSaJEJadytTayPth0d+v9Jo7WSWgfZULF/ZQJhx/zoURmHU7OO2iXlvB64LlA0W+Tl0v2i7MW57XAOv",
	"8j0FjQhSlC8YjHcLWhqwh2AH8/wkvDCWUH2+Yd002cMDZidU7kNphJtOV9/xipsAJ6mHqT4nEdGP0QmX",
	"aRd/7ZTnuU/89wCa9pqZsFFVPsI1vKeMoRmgVEGEZs5TqwYxIsPbMeWA7pc0XKLPZwiyWFvuVs6g2LKX",
	"AY2YJAnliyN0whgid4Qy06KYt9rZWFiI0BKMm8wEX7iAiYGk7JjVa3vVZq2O83k3197K1A69OehSlMig",
	"xsk2SM2JQF0kqELwGm0duZuBzw5yA2ouuTjuZL1xxwO5e74E9Muni3OUSYZyDBmLCJgX+bXkzYtx1Ye7",
	"VQ/+PXfIxptt20trXBePEiuIcseWcyFjoquCUZOCtmBMJLnvFQ4NX/QkYYQOiYUk96Ol4orcNwRjgH9K",
	"KOqc03QPDjxR8gRRliYGdQMMUda4dTvsjCHXzEvQrLzioOAepOAa1S/7udGoMVjOrBln9oSZJVgf0cYP",
	"bWt/RLlg0Ofw57N63O2GjyuT7lXM2EvwFr+Uam10OKmLfVy0yDHQIUpUixL1EGBM8KcD4YVGfO4Qz0H1",
	"dtDDp363Hcnp1OZpkzsOCv17iPKMV+bjdvY2u+3K5ut+sXGY7WhoSdSA9nmZ2/dtuKuHTflqIybblkol",
	"Olx6rmKKIiQkkrnd9oIsJnMp4h7NWxxZ8MnGZnq4rCy2R71OeOR8CsuIBXpPeJFiF3M0E65QjEQRIjzK",
	"V1MAWVSsG2yKBE+zwvnyYa14ML+toqwY9F4kUb16Iqg1Wd8YAbUTZbX51bkaLW/Wo29OGb72YN2+N+kp",
	"ZXzgjM7eSfkDpWfQjtHaQcxOf9nokrKpkQQyynU+q96JczBdk55bG/Y2ctjJV7tkrypAbmqkajLwEkzU",
	"NgyMz55sc6fTe/Ryz61LP68PmpTiEHivNbGtxhsSd+jhYEMqNqR+bHRvzYePkXZrp2MgLCSp2JUN2o2c",
	"5Q8mY9dMxp5L3nj+9tqKkVuOPKFcNveaiJe4w9it1O/BAepjuJyFK1zbnQo+sQq0qD/354EfsR/YrLbz",
	"W50m2k+N2KC7l2/q6m+DUwbdHOVSwyVPHdLDjUMEg0QZkybuxn9NgW7rQMCeJ4lHkPQbVP33aP3UxyMH",
	"xf89nQ94iO7fIIvcyuwVZ9y6Msh1jjtkkXsO4h9STKvRfLZNfTsmvFIBuIxW9irjytVrfuE4pJG/rzTy",
	"Qcy7ozcjxGe0NRuo4bf6xbWpaxaqEEExZN9/GmHMXlqp/5bM2L4Xkm7AYLtmxWrgjkswd4jEIVvQnS3Y",
	"mqXZd0ncjLlHG5j+zLIVf5cNJErRBYcovzBng/DNIdHsMy17nvEayVovxKqYhYwyKocM9A7ZlEPSeTxn",
	"d1oUWb27ubc+Kc8GlhdcFH3958mLkV9SGtr3KV2H1Wv3mcKSUT3n8lcJFEe+V5VPLNtPK3uU1nNaqvaX",
	"ivb+KH4H6+bCUcpCJhuj6vbywW1rvyS8LA9qt4oxDkV9fi4rmNYy18jD+B2OjlD6YZ7NyK8O27u1nz4D",
	"95iLvff5hH7TKchZqNB5g3UYrsai03N2ry1LHaovLP5bCGuL73DNhR/ZuY587lKLUor3tsyim3jbP4nf",
	"s2ets8PL0ecH7us8hz9OZY8rn8hdilpm2x4XGFYwh6qJDhf1kEpdjWKtLanOpzhxP6RhD5US33+lxEG0",
	"H3bevs9eqXuyWIA8yskx4spfWbmKtnrx7EUC/OTyzH5pKMiu+w3zS3rt/cBzIVEEs3SxoHwRoJkU98r+",
	"Z7pFVIXiDuQqsB+GaMn6JwfpLyr73skjOG3UpZid1+9W14mIQiS7WZTWsWy/FOe+faBA3uUqtT5RwkgI",
	"S8EikDjAqWR4ipdaJ2o6mVTeHYUinty9scYzG7+lTnlJIXvvsnk5c7Ho6t2/Rm1lX6QqlXrtcmCjQjy5",
	"S8JY85rp7FLlMpRXjti4X7o95gkKjQoL3beyqudaqram/CTs4ACLvMYg65z9Hu4os2hL1s/9HO4GdWNT",
	"DU8X36IcnrsSl8/nr35w/n8BAAD//7wXMCZdkAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
