// Package resources provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for CapabilityMethods.
const (
	DELETE CapabilityMethods = "DELETE"
	GET    CapabilityMethods = "GET"
	PATCH  CapabilityMethods = "PATCH"
	POST   CapabilityMethods = "POST"
	PUT    CapabilityMethods = "PUT"
)

// Defines values for GroupEntitlementsPatchItemOp.
const (
	GroupEntitlementsPatchItemOpAdd    GroupEntitlementsPatchItemOp = "add"
	GroupEntitlementsPatchItemOpRemove GroupEntitlementsPatchItemOp = "remove"
)

// Defines values for GroupIdentitiesPatchItemOp.
const (
	GroupIdentitiesPatchItemOpAdd    GroupIdentitiesPatchItemOp = "add"
	GroupIdentitiesPatchItemOpRemove GroupIdentitiesPatchItemOp = "remove"
)

// Defines values for GroupRolesPatchItemOp.
const (
	GroupRolesPatchItemOpAdd    GroupRolesPatchItemOp = "add"
	GroupRolesPatchItemOpRemove GroupRolesPatchItemOp = "remove"
)

// Defines values for IdentityEntitlementsPatchItemOp.
const (
	IdentityEntitlementsPatchItemOpAdd    IdentityEntitlementsPatchItemOp = "add"
	IdentityEntitlementsPatchItemOpRemove IdentityEntitlementsPatchItemOp = "remove"
)

// Defines values for IdentityGroupsPatchItemOp.
const (
	IdentityGroupsPatchItemOpAdd    IdentityGroupsPatchItemOp = "add"
	IdentityGroupsPatchItemOpRemove IdentityGroupsPatchItemOp = "remove"
)

// Defines values for IdentityProviderSyncMode.
const (
	Import IdentityProviderSyncMode = "import"
)

// Defines values for IdentityRolesPatchItemOp.
const (
	IdentityRolesPatchItemOpAdd    IdentityRolesPatchItemOp = "add"
	IdentityRolesPatchItemOpRemove IdentityRolesPatchItemOp = "remove"
)

// Defines values for RoleEntitlementsPatchItemOp.
const (
	Add    RoleEntitlementsPatchItemOp = "add"
	Remove RoleEntitlementsPatchItemOp = "remove"
)

// AvailableIdentityProvider defines model for AvailableIdentityProvider.
type AvailableIdentityProvider struct {
	Id   string  `json:"id"`
	Name *string `json:"name,omitempty"`
}

// AvailableIdentityProviders defines model for AvailableIdentityProviders.
type AvailableIdentityProviders struct {
	Data []AvailableIdentityProvider `json:"data"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Data []Capability `json:"data"`
}

// Capability defines model for Capability.
type Capability struct {
	Endpoint string              `json:"endpoint"`
	Methods  []CapabilityMethods `json:"methods"`
}

// CapabilityMethods defines model for Capability.Methods.
type CapabilityMethods string

// Entity defines model for Entity.
type Entity struct {
	Id   string `json:"id" validate:"required"`
	Type string `json:"type" validate:"required"`
}

// EntityEntitlement defines model for EntityEntitlement.
type EntityEntitlement struct {
	EntitlementType string `json:"entitlement_type" validate:"required"`
	EntityName      string `json:"entity_name" validate:"required"`
	EntityType      string `json:"entity_type" validate:"required"`
}

// EntityEntitlementItem defines model for EntityEntitlementItem.
type EntityEntitlementItem struct {
	Entitlement EntityEntitlement `json:"entitlement"`
}

// GetAvailableIdentityProvidersResponse defines model for GetAvailableIdentityProvidersResponse.
type GetAvailableIdentityProvidersResponse struct {
	Links   ResponseLinks               `json:"_links"`
	Meta    ResponseMeta                `json:"_meta"`
	Data    []AvailableIdentityProvider `json:"data"`
	Message string                      `json:"message"`
	Status  int                         `json:"status"`
}

// GetCapabilitiesResponse defines model for GetCapabilitiesResponse.
type GetCapabilitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Capability  `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetEntitlementsResponse defines model for GetEntitlementsResponse.
type GetEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupEntitlementsResponse defines model for GetGroupEntitlementsResponse.
type GetGroupEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetGroupIdentitiesResponse defines model for GetGroupIdentitiesResponse.
type GetGroupIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupRolesResponse defines model for GetGroupRolesResponse.
type GetGroupRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetGroupsResponse defines model for GetGroupsResponse.
type GetGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentitiesResponse defines model for GetIdentitiesResponse.
type GetIdentitiesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Identity    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityEntitlementsResponse defines model for GetIdentityEntitlementsResponse.
type GetIdentityEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetIdentityGroupsResponse defines model for GetIdentityGroupsResponse.
type GetIdentityGroupsResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Group       `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetIdentityProvidersResponse defines model for GetIdentityProvidersResponse.
type GetIdentityProvidersResponse struct {
	Links   ResponseLinks      `json:"_links"`
	Meta    ResponseMeta       `json:"_meta"`
	Data    []IdentityProvider `json:"data"`
	Message string             `json:"message"`
	Status  int                `json:"status"`
}

// GetIdentityRolesResponse defines model for GetIdentityRolesResponse.
type GetIdentityRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetResourcesResponse defines model for GetResourcesResponse.
type GetResourcesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Resource    `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// GetRoleEntitlementsResponse defines model for GetRoleEntitlementsResponse.
type GetRoleEntitlementsResponse struct {
	Links   ResponseLinks       `json:"_links"`
	Meta    ResponseMeta        `json:"_meta"`
	Data    []EntityEntitlement `json:"data"`
	Message string              `json:"message"`
	Status  int                 `json:"status"`
}

// GetRolesResponse defines model for GetRolesResponse.
type GetRolesResponse struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Data    []Role        `json:"data"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// Group defines model for Group.
type Group struct {
	Id   *string `json:"id,omitempty"`
	Name string  `json:"name" validate:"required"`
}

// GroupEntitlementsPatchItem defines model for GroupEntitlementsPatchItem.
type GroupEntitlementsPatchItem struct {
	Entitlement EntityEntitlement            `json:"entitlement"`
	Op          GroupEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupEntitlementsPatchItemOp defines model for GroupEntitlementsPatchItem.Op.
type GroupEntitlementsPatchItemOp string

// GroupEntitlementsPatchRequestBody defines model for GroupEntitlementsPatchRequestBody.
type GroupEntitlementsPatchRequestBody struct {
	Patches []GroupEntitlementsPatchItem `json:"patches" validate:"required,dive"`
}

// GroupIdentitiesPatchItem defines model for GroupIdentitiesPatchItem.
type GroupIdentitiesPatchItem struct {
	Identity string                     `json:"identity" validate:"required"`
	Op       GroupIdentitiesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// GroupIdentitiesPatchItemOp defines model for GroupIdentitiesPatchItem.Op.
type GroupIdentitiesPatchItemOp string

// GroupIdentitiesPatchRequestBody defines model for GroupIdentitiesPatchRequestBody.
type GroupIdentitiesPatchRequestBody struct {
	Patches []GroupIdentitiesPatchItem `json:"patches" validate:"required,dive"`
}

// GroupRolesPatchItem defines model for GroupRolesPatchItem.
type GroupRolesPatchItem struct {
	Op   GroupRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                `json:"role" validate:"required"`
}

// GroupRolesPatchItemOp defines model for GroupRolesPatchItem.Op.
type GroupRolesPatchItemOp string

// GroupRolesPatchRequestBody defines model for GroupRolesPatchRequestBody.
type GroupRolesPatchRequestBody struct {
	Patches []GroupRolesPatchItem `json:"patches" validate:"required,dive"`
}

// Groups defines model for Groups.
type Groups struct {
	Data []Group `json:"data"`
}

// Identities defines model for Identities.
type Identities struct {
	Data []Identity `json:"data"`
}

// Identity defines model for Identity.
type Identity struct {
	AddedBy     string  `json:"addedBy" validate:"required"`
	Certificate *string `json:"certificate,omitempty"`
	Email       string  `json:"email" validate:"required"`
	FirstName   *string `json:"firstName,omitempty"`
	Groups      *int    `json:"groups,omitempty"`
	Id          *string `json:"id,omitempty"`
	Joined      *string `json:"joined,omitempty"`
	LastLogin   *string `json:"lastLogin,omitempty"`
	LastName    *string `json:"lastName,omitempty"`
	Permissions *int    `json:"permissions,omitempty"`
	Roles       *int    `json:"roles,omitempty"`
	Source      string  `json:"source" validate:"required"`
}

// IdentityEntitlementsPatchItem defines model for IdentityEntitlementsPatchItem.
type IdentityEntitlementsPatchItem struct {
	Entitlement EntityEntitlement               `json:"entitlement"`
	Op          IdentityEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityEntitlementsPatchItemOp defines model for IdentityEntitlementsPatchItem.Op.
type IdentityEntitlementsPatchItemOp string

// IdentityEntitlementsPatchRequestBody defines model for IdentityEntitlementsPatchRequestBody.
type IdentityEntitlementsPatchRequestBody struct {
	Patches []IdentityEntitlementsPatchItem `json:"patches" validate:"required,dive"`
}

// IdentityGroupsPatchItem defines model for IdentityGroupsPatchItem.
type IdentityGroupsPatchItem struct {
	Group string                    `json:"group" validate:"required"`
	Op    IdentityGroupsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// IdentityGroupsPatchItemOp defines model for IdentityGroupsPatchItem.Op.
type IdentityGroupsPatchItemOp string

// IdentityGroupsPatchRequestBody defines model for IdentityGroupsPatchRequestBody.
type IdentityGroupsPatchRequestBody struct {
	Patches []IdentityGroupsPatchItem `json:"patches" validate:"required,dive"`
}

// IdentityProvider defines model for IdentityProvider.
type IdentityProvider struct {
	AcceptsPromptNone   *bool                     `json:"acceptsPromptNone,omitempty"`
	AccountLinkingOnly  *bool                     `json:"accountLinkingOnly,omitempty"`
	ClientID            *string                   `json:"clientID,omitempty"`
	ClientSecret        *string                   `json:"clientSecret,omitempty"`
	DisableIdentityInfo *bool                     `json:"disableIdentityInfo,omitempty"`
	Enabled             *bool                     `json:"enabled,omitempty"`
	Id                  *string                   `json:"id,omitempty"`
	IdentityCount       *int                      `json:"identityCount,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	RedirectUrl         *string                   `json:"redirectUrl,omitempty"`
	StoreTokens         *bool                     `json:"storeTokens,omitempty"`
	StoreTokensReadable *bool                     `json:"storeTokensReadable,omitempty"`
	SyncMode            *IdentityProviderSyncMode `json:"syncMode,omitempty" validate:"oneof=import"`
	TrustEmail          *bool                     `json:"trustEmail,omitempty"`
}

// IdentityProviderSyncMode defines model for IdentityProvider.SyncMode.
type IdentityProviderSyncMode string

// IdentityProviders defines model for IdentityProviders.
type IdentityProviders struct {
	Data []IdentityProvider `json:"data"`
}

// IdentityRolesPatchItem defines model for IdentityRolesPatchItem.
type IdentityRolesPatchItem struct {
	Op   IdentityRolesPatchItemOp `json:"op" validate:"required,oneof=add remove"`
	Role string                   `json:"role" validate:"required"`
}

// IdentityRolesPatchItemOp defines model for IdentityRolesPatchItem.Op.
type IdentityRolesPatchItemOp string

// IdentityRolesPatchRequestBody defines model for IdentityRolesPatchRequestBody.
type IdentityRolesPatchRequestBody struct {
	Patches []IdentityRolesPatchItem `json:"patches" validate:"required,dive"`
}

// Resource defines model for Resource.
type Resource struct {
	Entity Entity    `json:"entity"`
	Id     string    `json:"id"`
	Name   string    `json:"name"`
	Parent *Resource `json:"parent,omitempty"`
}

// Resources defines model for Resources.
type Resources struct {
	Data []Resource `json:"data"`
}

// Response defines model for Response.
type Response struct {
	Links   ResponseLinks `json:"_links"`
	Meta    ResponseMeta  `json:"_meta"`
	Message string        `json:"message"`
	Status  int           `json:"status"`
}

// ResponseLinks defines model for ResponseLinks.
type ResponseLinks struct {
	Next ResponseLinksNext `json:"next"`
}

// ResponseLinksNext defines model for ResponseLinksNext.
type ResponseLinksNext struct {
	Href string `json:"href"`
}

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Page      *int    `json:"page,omitempty"`
	PageToken *string `json:"pageToken,omitempty"`
	Size      int     `json:"size"`
	Total     *int    `json:"total,omitempty"`
}

// Role defines model for Role.
type Role struct {
	Entitlements *[]RoleEntitlement `json:"entitlements,omitempty" validate:"dive"`
	Id           *string            `json:"id,omitempty"`
	Name         string             `json:"name" validate:"required"`
}

// RoleEntitlement defines model for RoleEntitlement.
type RoleEntitlement struct {
	Entitlement *string `json:"entitlement,omitempty"`
	Entity      *Entity `json:"entity,omitempty"`
	Resource    *string `json:"resource,omitempty"`
}

// RoleEntitlementsPatchItem defines model for RoleEntitlementsPatchItem.
type RoleEntitlementsPatchItem struct {
	Entitlement EntityEntitlement           `json:"entitlement"`
	Op          RoleEntitlementsPatchItemOp `json:"op" validate:"required,oneof=add remove"`
}

// RoleEntitlementsPatchItemOp defines model for RoleEntitlementsPatchItem.Op.
type RoleEntitlementsPatchItemOp string

// RoleEntitlementsPatchRequestBody defines model for RoleEntitlementsPatchRequestBody.
type RoleEntitlementsPatchRequestBody struct {
	Patches []RoleEntitlementsPatchItem `json:"patches" validate:"required,dive"`
}

// Roles defines model for Roles.
type Roles struct {
	Data []Role `json:"data"`
}

// FilterParam defines model for FilterParam.
type FilterParam = string

// PaginationNextToken defines model for PaginationNextToken.
type PaginationNextToken = string

// PaginationNextTokenHeader defines model for PaginationNextTokenHeader.
type PaginationNextTokenHeader = string

// PaginationPage defines model for PaginationPage.
type PaginationPage = int

// PaginationSize defines model for PaginationSize.
type PaginationSize = int

// BadRequest defines model for BadRequest.
type BadRequest = Response

// NotFound defines model for NotFound.
type NotFound = Response

// Unauthorized defines model for Unauthorized.
type Unauthorized = Response

// Default defines model for default.
type Default = Response

// GetIdentityProvidersParams defines parameters for GetIdentityProviders.
type GetIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetAvailableIdentityProvidersParams defines parameters for GetAvailableIdentityProviders.
type GetAvailableIdentityProvidersParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetEntitlementsParams defines parameters for GetEntitlements.
type GetEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsParams defines parameters for GetGroups.
type GetGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemEntitlementsParams defines parameters for GetGroupsItemEntitlements.
type GetGroupsItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemIdentitiesParams defines parameters for GetGroupsItemIdentities.
type GetGroupsItemIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetGroupsItemRolesParams defines parameters for GetGroupsItemRoles.
type GetGroupsItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesParams defines parameters for GetIdentities.
type GetIdentitiesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemEntitlementsParams defines parameters for GetIdentitiesItemEntitlements.
type GetIdentitiesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemGroupsParams defines parameters for GetIdentitiesItemGroups.
type GetIdentitiesItemGroupsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetIdentitiesItemRolesParams defines parameters for GetIdentitiesItemRoles.
type GetIdentitiesItemRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetResourcesParams defines parameters for GetResources.
type GetResourcesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken  *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`
	EntityType *string              `form:"entityType,omitempty" json:"entityType,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesParams defines parameters for GetRoles.
type GetRolesParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// Filter A string to filter results by
	Filter *FilterParam `form:"filter,omitempty" json:"filter,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// GetRolesItemEntitlementsParams defines parameters for GetRolesItemEntitlements.
type GetRolesItemEntitlementsParams struct {
	// Size The number of records to return per response
	Size *PaginationSize `form:"size,omitempty" json:"size,omitempty"`

	// Page The record offset to return results from
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// NextToken The continuation token to retrieve the next set of results
	NextToken *PaginationNextToken `form:"nextToken,omitempty" json:"nextToken,omitempty"`

	// NextPageToken The continuation token to retrieve the next set of results
	NextPageToken *PaginationNextTokenHeader `json:"Next-Page-Token,omitempty"`
}

// PostIdentityProvidersJSONRequestBody defines body for PostIdentityProviders for application/json ContentType.
type PostIdentityProvidersJSONRequestBody = IdentityProvider

// PutIdentityProvidersItemJSONRequestBody defines body for PutIdentityProvidersItem for application/json ContentType.
type PutIdentityProvidersItemJSONRequestBody = IdentityProvider

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody = Group

// PutGroupsItemJSONRequestBody defines body for PutGroupsItem for application/json ContentType.
type PutGroupsItemJSONRequestBody = Group

// PatchGroupsItemEntitlementsJSONRequestBody defines body for PatchGroupsItemEntitlements for application/json ContentType.
type PatchGroupsItemEntitlementsJSONRequestBody = GroupEntitlementsPatchRequestBody

// PatchGroupsItemIdentitiesJSONRequestBody defines body for PatchGroupsItemIdentities for application/json ContentType.
type PatchGroupsItemIdentitiesJSONRequestBody = GroupIdentitiesPatchRequestBody

// PatchGroupsItemRolesJSONRequestBody defines body for PatchGroupsItemRoles for application/json ContentType.
type PatchGroupsItemRolesJSONRequestBody = GroupRolesPatchRequestBody

// PostIdentitiesJSONRequestBody defines body for PostIdentities for application/json ContentType.
type PostIdentitiesJSONRequestBody = Identity

// PutIdentitiesItemJSONRequestBody defines body for PutIdentitiesItem for application/json ContentType.
type PutIdentitiesItemJSONRequestBody = Identity

// PatchIdentitiesItemEntitlementsJSONRequestBody defines body for PatchIdentitiesItemEntitlements for application/json ContentType.
type PatchIdentitiesItemEntitlementsJSONRequestBody = IdentityEntitlementsPatchRequestBody

// PatchIdentitiesItemGroupsJSONRequestBody defines body for PatchIdentitiesItemGroups for application/json ContentType.
type PatchIdentitiesItemGroupsJSONRequestBody = IdentityGroupsPatchRequestBody

// PatchIdentitiesItemRolesJSONRequestBody defines body for PatchIdentitiesItemRoles for application/json ContentType.
type PatchIdentitiesItemRolesJSONRequestBody = IdentityRolesPatchRequestBody

// PostRolesJSONRequestBody defines body for PostRoles for application/json ContentType.
type PostRolesJSONRequestBody = Role

// PutRolesItemJSONRequestBody defines body for PutRolesItem for application/json ContentType.
type PutRolesItemJSONRequestBody = Role

// PatchRolesItemEntitlementsJSONRequestBody defines body for PatchRolesItemEntitlements for application/json ContentType.
type PatchRolesItemEntitlementsJSONRequestBody = RoleEntitlementsPatchRequestBody

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PbuJL+KyjsPk3RlrMn++KqrVpPJpPx2UzsSpzah4wrBZEtCWMS4ACgbZ2U/vsp",
	"AASvIEXdbI/FF1sScWk0vr6g0QB/4JAnKWfAlMTnP3BKBElAgTDffqWxAnGtf9NfI5ChoKminOFzfIGk",
	"EpTNkeJoZgoiATKLlUTTJQ4w1YX+ykDoL4wkgM+xLYcDLMMFJEQ3qpapfmLbwqtVgK/JnDKie/kEj+qG",
	"3wFr936zABRypijLTFGkdDlNiwAlKNwDUgtADB4VkqAQnznqOkhjRV8bU/cbkAjEIWhc2JYLInWXJ9dk",
	"Diebkaqr+OkTEHIRIT6baQosaZlgxVTOBE86OJbqRqsUJJTRJEvw+ZvAUUOZgjmIBjlf6L86yGFZMgVh",
	"OaEJkxWSUouwlDMJHSRJ3XCNJPKYk3R2FvQTuAqwa92A/2cSfYa/MpBKf9PzCMx8JGka09AMZPKn5Aac",
	"8EiSNDaD+h5Tdmda0BOr/y8EzPA5Nkz4noAiVtL0lJwFlmb9QXFFYnx+tgpwRHShb7cBTkBKU1LTg0RO",
	"UIClIiqT+PztmS5fDvg/bV//MSnlemKfyslnxzwz2DrzdetuuKsAf+LqV56x6GUM/RNXaGbIqQ787V4G",
	"Xra9CvBXRjK14IL+C17I0GsUVUf/Zi+jrzVvns5IFquXMnZ4TCFUECEQgovK+P97T7BvdbEqmjUDurgn",
	"NCbTGC4jYIqq5bXg9zTX9qngKQhFrb6gkUcLO83kU89amKnQQPumK98WOolP/4TQiGFn97Ldv+XgD0wV",
	"JHIdT7rHtSrIIEKQZYtS042P1nckJVMaU0dPDhCJz7854r79wMCilFMNKzyhtm9dXk+7WvBIl8Yf3t/g",
	"29Xt6jbYZYgFPcs9jGnZ5nc5Es+sF6OpEAtMmx47vABfX30x/77qv7+8//j+5r3+enHz7rcKKWWLvQMo",
	"aCl79g3nvZnq1uRo5OIso1rB5HW08AsexxoQrWnwIT3AjyecpPQk5BHMgZ3AoxLkRJG5qXJPYhoRpSsU",
	"dK+KUe2lsQZLTItBl2BZTpi/MSS5mmvOb/Hw+x7JDGzDy+9+xbBbm4djZ7WD+hCCNqcGcfxSQdLL9XUC",
	"3p5DL9H5Mx9NH0B1a9jCbGgDGMdXMyMrwwxNsKX2lXh1a+mqatMDUlJT2q7vCkt37XsH/e2Z3u3UeD6q",
	"D4Jn6Sse2mVhTQ+Il7KTeuefeXzQfk379S4P2Z3toOjvuVjr1MPrRK0b3TPN5pNo+m4F7548reR8Bskz",
	"ER62R9dH2SuP4XVi+ClnT6N4x2XnPjxB07LXm2oa2GuiwoVz84Yxxu8ltiedp9UVFYn00kVAwu+hvXja",
	"fNABZ8Bn/0OiCOWNtrjA0y5QeLmQh9Z+5pFnJZnqEiAHg7iH0U00bzH2iPrG62jsnPjSfNWmvQlWKJag",
	"e1n3PDsOihEFfkj4ubN/OPjY/3xgMGqrBwdPP20BFjw+kEY0LffPf8mQ/U99g9nPN+u7BiWthds6WFdx",
	"oHejw7lmO5PimWESRRD93IzBYX5Xa2k3pRjq7mY0NI88vgEkhMZ7U8EzKqT65I9yB3heAKO54RZ0uS5/",
	"csrA/ygmUn3kc8o6n3YSkoJIqJSUsw5qhHG1vI+sP9ucM3hUIBiJzV5k/nE/U9gMY5n5KsgIChD1Qe/o",
	"HbFORuxVA/ez+1l0cX1d3WOF525F8TpcMTucTjvsYctBkNBk+7NioHu7koQhpEpeC56k6hNnVa055TwG",
	"wnRDJAx5xtRHyu4om1+xeOkvF8ZUK4lfvLrXPvwCoQD/dllEZTUcfslm3N8NMF0u8j/ssCfORX+nB+JX",
	"8KzLagiIqIBQfRWx97lUXIDJxZF+mioFPgOJNPUdBZcs/J1HUBUimqRcqF3Ex0pN3o7ZcBOZVO8bDkBB",
	"xmoAlPblXe2+41wLoY2rjQ6eHETJvYQ1h4szdmwiLofFAnsUh9MKVaePPMgJZCcPIJV3mz4lYsDWZUG6",
	"Jw8k79dtsvYOfVdZLOnYVgarsc86IWVW0JBI6EdTuJouNKTW77rsqpIz5FXRNmXohy8nsTrGvKAjIXAj",
	"KJvvY8BHN9o6F1xG1GAefNIVWjFX/ePa3j/lfdUpsLlY6xKQTKm+Hn53WVwN/VHjesWk6idF7m57UvIM",
	"0Ha9PCds/WzpFrwE55q3M69guLZr7FvsoOZy7Ra8oHB9c3DrUjHaYYQNtayo6Os2GNfRd5yLWC8T9mrR",
	"u9n8PEbdRWF2sWpaA2xp0YyM5suPkDNFQgP+PGSG4+wOTh9AxrA8WfA4huX/hoRxRkMSn4YmVT5PRf+Y",
	"3QH6f1vyN1MSt7JPbxaAZjyO+QNlcyRTCG3YjnKGeKZiykCaIwIX15fIEY9mXJgff/1wgUiUUEalErbS",
	"TJik3QgpjkxMioQKPVC1QIShqxSYrkOZVISFgNRC8Gy+QASlgkdZqKTu6BTdLKhEVOo6cM/j+zZxRCIB",
	"s9gmzlJmyLkHIfUzm8J/+gfDATawwuf4neNRQcRFnfBrSwB6x5OUKGpzLjU1OMB5w/gcn52enb45wybY",
	"AIykFJ/jf5y+OT3D2t6ohUHGhGRqoXWTpdUEOuyys8l8KpFLnEQxlUoiEscoX2Jqntj1jh2KRqNp8DLC",
	"5940AkNEeXymQzeVRSaNAxFde8HeGuZEx0Y1ysM021XLT7msbhvnJP7r7GxAuviwVO3e7AxP+vbV/2kw",
	"vLUU+BouKJ1UjnOYKm/WV2kmx789e7u+UnFyop5N31/JFTTZ51mSELHUKoRKhULOZnSeacGvA7sCUC1p",
	"Rgt/ww3waxuScumB/zvXLiKIwUNX46ct6F9z6cW+qFulveChHSuoq3ElMlgdEI/+/o8JgxvApBOCq6Cp",
	"lCdpNZg0QD3LBc/iyJ0EI0ZdIz5z/Ut0x/iDOVqnTZFcSgVJYCxlvnhHV3eKBOgD5/MYAvSBqt+yKQIV",
	"nv6RnZ39I5wKNDGf4A/20083V79c/fTTOTpBX4zdW5pm8961x+A3CT15vaNt2INtGJCsfXQC+tmA0rqJ",
	"TipklqZcGN8sZ9RAY+GR1B80WlnpjEF5Tm1+Nksa7St2qIbCgpmf2/bkF9Nwa0bNEsQPp+Oa3o3Z2+MK",
	"eDXtB1CIIEnZPIbhboDPVeuZs9Ec7wUOQ+eqzx2s2yFzjFovnsqlK41w08nqO2h+G+A08+DqaxoRtYtm",
	"uM56IDY6m68P3VsgpteUhY0jqQMczQcax2gKKJMQoan1+6pRlUhLTkIZoIcFDRfo6yWCPHLmnNQpFDGE",
	"MsKSkDSlbH6KLuIYEefHFP1WK2srDhFagHa6Y87mNoKjKSkr5sc8vXq5dqjrsB6Z95haB27Xui0lM6h2",
	"2TVT3SRQG5qqTHhtbu10N2P8HdMNqDnk4loJ49tbDDhnfwHon1+uPqFcMqQFZMIjiL3Mr8ZSj8TrX1+5",
	"epHMoRcJ3oMmR+ko1GWr5AqizGJ6xkVCVFWqaiLUlqqJIA+9kqXgUU3SmNB1MiXIw2CR+kweGlK1Bj8l",
	"FXXkND2XERMlJog0c6JZtwYQZUpv93IijpEt5p3QPFt81I5Prx0bhy2PcwFVQ6dDeg7rnoi5AOOdmjio",
	"Ke0PjhfoPsQiJT8j8bQrk0qnRxX79k54Cy+lThwcLOuCj42FWQCNAbBaAKxnAobEtToYXmjEQ4euRtXb",
	"MR8+9fvUEapObZ410TEq9NcQXxquzIfFFMxGvT0oUHeqtbdtWkMLItdonyMMHDyFrzuGA5YbIfSp9DFR",
	"4cJzqXAUIS7yPElE/CTzyUzwpEdt67Y7BWszJV7m/puzuxcssg6JAWLB3gtW5BnwGZpym3BHoggR5rI+",
	"UUEkDvA9iTOopWt+ayXcti+gq/50on86IY3L2PIiyxP9rfq02sDS1c1P7ZmMVy3JWxAw7SVg2kvAtCDA",
	"5cXerlaDr/Vcf9HGqn2p7xE60FuK1FrLSGvH7Ts9cK1gyqJaPMggZ/yyejnoaAz3Yww9F5kdbRS0E5Qv",
	"yQJWiNzU7NUE6OUavfJKoOKjsVs1w+QrNMW7Go+eS3mGr8eO15T0Y3Ot/Sju2+g1HabUcKthj4+MBmNf",
	"BqN+v93R2gofCl/WQklTWIhhsahbayScvLxc+1DYAXem3vwzi5cfNf1ffz7dwh74z8yPpmDIqqIbf15D",
	"MHDx4Haqy+J9iajHs1Z4WXvK46qiD60O/xXId+8xXxjtWKTt956+2saz3ywT9bkyYI8PPp559+Kmrjs3",
	"OJzRjaja+QsK475z8+DF2kkZsv/czf+aAn2qExRHvvs8YEqf4ZhEj9bPfBgZFf9rOvKwje7fYHu6tetX",
	"HA3s2pquI27cnj7UTQfjDvVyMEifUlkPCbxUCC6DoL2a3Fyv0ydZ4/7069ifHnT/8LhFvdxGpgbbxzVn",
	"FYzSsWXq6oZKRFAC+cuIB5jHozrS8ESG8dgTZjdA50uzizVynRB3nQjy2MQtz1A8pTXMb0+3/9tb1vXH",
	"O21Wr7m5fLQhy03xN9h+9G9SGwG1e4NESjpnELkriDaI94x71nu3HEe+bT0Ql38Lo2GGMchmjHvZXXe0",
	"j9ZiC2tRAK/TWIjqLey9WUxuZ7C8v6Oo6z/xXrR8NPvZRs38lYFYlnrGzsiNfed4CX7PtQPLFIoT7XoK",
	"0czsf6PpEgc+fXRII9R+x+rR3zTQgXsnWaUg5YI1KDXQNd5hIdzbWceUkGdICRnzBv0QLRBvkDnwrgFd",
	"2J8Jsp3LM2wW7S3q+98H3OUK92O+gMChoAmhQmGuzQaxmR55sl5XIoiB1JgDYvjfYlhbfNdnfviZ7XTk",
	"oRM+Sik+2mSP7sl7+osGOlR51gDD30ebj9jrvGRgmMIelsLhHIraBrk5j7BevYyZG4fwbsesjeUgXD6R",
	"1t3HdQIdytlE0DqEaUzWeB3JGmvfszWGTZdby5PPAMoHMp+DOHWiMeBqZlG5Mrh6QfBVCuzi+tK8oirI",
	"r2UO3WXK5h7nGRcogmk2n1M2D9BU8AdpPulqEZUhvwexDMzrQFry/8VS+k9pZG0nszLo/tHOa5Kr40RE",
	"IpJf4krrXDYvr8yxD+Leqdl6R2lMQljwWFvLAGcixud4oVQqzyeTyrPTkCeT+zfGoObtt1QsK2fI3I+t",
	"H05tTL16R7PWZfmrzEpFX7vEWSsNz/4qiePmdeD55ddlWLFssXEPeLvNCxTyOIbQvmStelinan+K39Y3",
	"MHepCnnl/Pv6iiIP3uT17Nf11aBugaqK0v06oO/KBoPrv/hpdbv6dwAAAP//yhb0cxigAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
