image:
  repository: bitnamilegacy/postgresql
global:
  postgresql:
    auth:
      database: "iam"
      username: "iam"
      password: "iam"
      postgresPassword: "iam"
primary:
  initdb:
    scripts:
      init.sql: |
        CREATE DATABASE kratos;
        CREATE DATABASE hydra;
        CREATE DATABASE openfga;
        CREATE DATABASE "admin-service";

auth:
  database: "iam"
  username: "iam"
  password: "iam"
  postgresPassword: "iam"
