run-name: Unit test steps for ${{ github.sha }} on ${{ github.ref_name }}

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        name: Checkout repo

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        name: Setup Go version
        with:
          go-version: '1.21'

      - uses: golangci/golangci-lint-action@v3
        name: Perform linting and annotate code
        with:
          version: latest
          working-directory: ./rebac-admin-backend
          only-new-issues: true
