name: container scan
run-name: Scanning container ${{ inputs.image }} to ghcr.io/canonical/identity-platform-admin-ui

on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
        description: "image to scan"
jobs:
  scan:
    permissions:
      packages: read
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@c03d123cb480c08c69b054af418ea5e69fe6e57e # master
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload scan results to GitHub
      uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d # v4
      with:
        sarif_file: 'trivy-results.sarif'