name: TIOBE Quality Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 1 * *'

jobs:
  TICS:
    runs-on: [ self-hosted, amd64, tiobe, noble ]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: '1.26'
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
      - name: Install dependencies
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.6.1
          go install github.com/axw/gocov/gocov@v1.1.0
          go install github.com/AlekSi/gocov-xml@v1.1.0

      # We could store a report from the regular run, but this is cheap to do and keeps this isolated.
      - name: Test and generate coverage report
        run: |
          make npm-build test
          gocov convert coverage.out > coverage.json
          # Annoyingly, the coverage.xml file needs to be in a .coverage folder.
          mkdir .coverage ui/coverage
          gocov-xml < coverage.json > .coverage/coverage.xml

      - name: Get repo name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@a53037a6bb9f71b6a97cdeb0ac41632266804b9e # v3
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=GoProjects
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: ${{ env.REPO_NAME }}
          installTics: true
